name: "sqlite3-amalg"

on:
  push:
    branches:
      - '*'

jobs:
    build-linux:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Build sqlite3 lib for Linux
          run: |
            ./build-sqlite3.sh linux
        
        - name: Archive results
          uses: actions/upload-artifact@v3
          with:
            name: Linux sqlite3
            path: |
              ./libsqlite3.a
    build-windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - uses: ilammy/msvc-dev-cmd@v1.4.1
        - name: Build sqlite3 lib for Win64
          run: ./build-sqlite3.sh win64
          shell: bash
           
        - name: Archive results
          uses: actions/upload-artifact@v3
          with:
            name: Windows sqlite3
            path: |
              ./libsqlite3.lib
    build-macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
        - name: Build sqlite lib for macos
          run: ./build-sqlite3.sh macosx
              
        - name: Archive results
          uses: actions/upload-artifact@v3
          with:
            name: macOS sqlite3
            path: |
              ./libsqlite3.a
    build-ios64:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
        - name: Build sqlite lib for iosarm64
          run: ./build-sqlite3.sh ios64
              
        - name: Archive results
          uses: actions/upload-artifact@v3
          with:
            name: ios64 sqlite3
            path: |
              ./libsqlite3.a
    build-android:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Fetch NDK
          run: wget https://dl.google.com/android/repository/android-ndk-r26b-linux.zip
        - name: Install arm compiler
          run: unzip android-ndk-r26b-linux.zip
        - name: Build sqlite lib for android
          run: ./build-sqlite3.sh android
              
        - name: Archive results
          uses: actions/upload-artifact@v3
          with:
            name: android sqlite3
            path: |
              ./libsqlite3.a              
        - name: Archive armv7 results
          uses: actions/upload-artifact@v3
          with:
            name: android sqlite3
            path: |
              ./libsqlite3-armv7.a              
