name: "sqlite3-amalg"

on:
  push:
    branches:
      - '*'

jobs:
    build-linux:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Build sqlite3 lib for Linux
          run: |
            ./build-sqlite3.sh linux
        
        - name: Archive results
          uses: actions/upload-artifact@v3
          with:
            name: Linux sqlite3
            path: |
              ./sqlite3
    build-windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - uses: ilammy/msvc-dev-cmd@v1.4.1
        - name: Build sqlite3 lib for Win64
          run: ./build-sqlite3.sh win64
          shell: bash
           
        - name: Archive results
          uses: actions/upload-artifact@v3
          with:
            name: Windows sqlite3
            path: |
              ./sqlite3.exe
    build-macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
        - name: Build sqlite lib for macos
          run: ./build-sqlite3.sh macosx
              
        - name: Archive results
          uses: actions/upload-artifact@v3
          with:
            name: macOS sqlite3
            path: |
              ./sqlite3
